#pragma once

#include <map>
#include <string>

#include "cupti.h"

std::map<CUpti_ActivityKind, std::string> ACTIVITY_KIND_ENUM_MAP = {
    {CUPTI_ACTIVITY_KIND_INVALID, "CUPTI_ACTIVITY_KIND_INVALID"},
    {CUPTI_ACTIVITY_KIND_MEMCPY, "CUPTI_ACTIVITY_KIND_MEMCPY"},
    {CUPTI_ACTIVITY_KIND_MEMSET, "CUPTI_ACTIVITY_KIND_MEMSET"},
    {CUPTI_ACTIVITY_KIND_KERNEL, "CUPTI_ACTIVITY_KIND_KERNEL"},
    {CUPTI_ACTIVITY_KIND_DRIVER, "CUPTI_ACTIVITY_KIND_DRIVER"},
    {CUPTI_ACTIVITY_KIND_RUNTIME, "CUPTI_ACTIVITY_KIND_RUNTIME"},
    {CUPTI_ACTIVITY_KIND_EVENT, "CUPTI_ACTIVITY_KIND_EVENT"},
    {CUPTI_ACTIVITY_KIND_METRIC, "CUPTI_ACTIVITY_KIND_METRIC"},
    {CUPTI_ACTIVITY_KIND_DEVICE, "CUPTI_ACTIVITY_KIND_DEVICE"},
    {CUPTI_ACTIVITY_KIND_CONTEXT, "CUPTI_ACTIVITY_KIND_CONTEXT"},
    {CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL,
     "CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL"},
    {CUPTI_ACTIVITY_KIND_NAME, "CUPTI_ACTIVITY_KIND_NAME"},
    {CUPTI_ACTIVITY_KIND_MARKER, "CUPTI_ACTIVITY_KIND_MARKER"},
    {CUPTI_ACTIVITY_KIND_MARKER_DATA, "CUPTI_ACTIVITY_KIND_MARKER_DATA"},
    {CUPTI_ACTIVITY_KIND_SOURCE_LOCATOR, "CUPTI_ACTIVITY_KIND_SOURCE_LOCATOR"},
    {CUPTI_ACTIVITY_KIND_GLOBAL_ACCESS, "CUPTI_ACTIVITY_KIND_GLOBAL_ACCESS"},
    {CUPTI_ACTIVITY_KIND_BRANCH, "CUPTI_ACTIVITY_KIND_BRANCH"},
    {CUPTI_ACTIVITY_KIND_OVERHEAD, "CUPTI_ACTIVITY_KIND_OVERHEAD"},
    {CUPTI_ACTIVITY_KIND_CDP_KERNEL, "CUPTI_ACTIVITY_KIND_CDP_KERNEL"},
    {CUPTI_ACTIVITY_KIND_PREEMPTION, "CUPTI_ACTIVITY_KIND_PREEMPTION"},
    {CUPTI_ACTIVITY_KIND_ENVIRONMENT, "CUPTI_ACTIVITY_KIND_ENVIRONMENT"},
    {CUPTI_ACTIVITY_KIND_EVENT_INSTANCE, "CUPTI_ACTIVITY_KIND_EVENT_INSTANCE"},
    {CUPTI_ACTIVITY_KIND_MEMCPY2, "CUPTI_ACTIVITY_KIND_MEMCPY2"},
    {CUPTI_ACTIVITY_KIND_METRIC_INSTANCE,
     "CUPTI_ACTIVITY_KIND_METRIC_INSTANCE"},
    {CUPTI_ACTIVITY_KIND_INSTRUCTION_EXECUTION,
     "CUPTI_ACTIVITY_KIND_INSTRUCTION_EXECUTION"},
    {CUPTI_ACTIVITY_KIND_UNIFIED_MEMORY_COUNTER,
     "CUPTI_ACTIVITY_KIND_UNIFIED_MEMORY_COUNTER"},
    {CUPTI_ACTIVITY_KIND_FUNCTION, "CUPTI_ACTIVITY_KIND_FUNCTION"},
    {CUPTI_ACTIVITY_KIND_MODULE, "CUPTI_ACTIVITY_KIND_MODULE"},
    {CUPTI_ACTIVITY_KIND_DEVICE_ATTRIBUTE,
     "CUPTI_ACTIVITY_KIND_DEVICE_ATTRIBUTE"},
    {CUPTI_ACTIVITY_KIND_SHARED_ACCESS, "CUPTI_ACTIVITY_KIND_SHARED_ACCESS"},
    {CUPTI_ACTIVITY_KIND_PC_SAMPLING, "CUPTI_ACTIVITY_KIND_PC_SAMPLING"},
    {CUPTI_ACTIVITY_KIND_PC_SAMPLING_RECORD_INFO,
     "CUPTI_ACTIVITY_KIND_PC_SAMPLING_RECORD_INFO"},
    {CUPTI_ACTIVITY_KIND_INSTRUCTION_CORRELATION,
     "CUPTI_ACTIVITY_KIND_INSTRUCTION_CORRELATION"},
    {CUPTI_ACTIVITY_KIND_OPENACC_DATA, "CUPTI_ACTIVITY_KIND_OPENACC_DATA"},
    {CUPTI_ACTIVITY_KIND_OPENACC_LAUNCH, "CUPTI_ACTIVITY_KIND_OPENACC_LAUNCH"},
    {CUPTI_ACTIVITY_KIND_OPENACC_OTHER, "CUPTI_ACTIVITY_KIND_OPENACC_OTHER"},
    {CUPTI_ACTIVITY_KIND_CUDA_EVENT, "CUPTI_ACTIVITY_KIND_CUDA_EVENT"},
    {CUPTI_ACTIVITY_KIND_STREAM, "CUPTI_ACTIVITY_KIND_STREAM"},
    {CUPTI_ACTIVITY_KIND_SYNCHRONIZATION,
     "CUPTI_ACTIVITY_KIND_SYNCHRONIZATION"},
    {CUPTI_ACTIVITY_KIND_EXTERNAL_CORRELATION,
     "CUPTI_ACTIVITY_KIND_EXTERNAL_CORRELATION"},
    {CUPTI_ACTIVITY_KIND_NVLINK, "CUPTI_ACTIVITY_KIND_NVLINK"},
    {CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT,
     "CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT"},
    {CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE,
     "CUPTI_ACTIVITY_KIND_INSTANTANEOUS_EVENT_INSTANCE"},
    {CUPTI_ACTIVITY_KIND_INSTANTANEOUS_METRIC,
     "CUPTI_ACTIVITY_KIND_INSTANTANEOUS_METRIC"},
    {CUPTI_ACTIVITY_KIND_INSTANTANEOUS_METRIC_INSTANCE,
     "CUPTI_ACTIVITY_KIND_INSTANTANEOUS_METRIC_INSTANCE"},
    {CUPTI_ACTIVITY_KIND_MEMORY, "CUPTI_ACTIVITY_KIND_MEMORY"},
    {CUPTI_ACTIVITY_KIND_PCIE, "CUPTI_ACTIVITY_KIND_PCIE"},
    {CUPTI_ACTIVITY_KIND_OPENMP, "CUPTI_ACTIVITY_KIND_OPENMP"},
    {CUPTI_ACTIVITY_KIND_INTERNAL_LAUNCH_API,
     "CUPTI_ACTIVITY_KIND_INTERNAL_LAUNCH_API"},
    {CUPTI_ACTIVITY_KIND_MEMORY2, "CUPTI_ACTIVITY_KIND_MEMORY2"},
    {CUPTI_ACTIVITY_KIND_MEMORY_POOL, "CUPTI_ACTIVITY_KIND_MEMORY_POOL"},
    {CUPTI_ACTIVITY_KIND_GRAPH_TRACE, "CUPTI_ACTIVITY_KIND_GRAPH_TRACE"},
    {CUPTI_ACTIVITY_KIND_COUNT, "CUPTI_ACTIVITY_KIND_COUNT"},
    {CUPTI_ACTIVITY_KIND_FORCE_INT, "CUPTI_ACTIVITY_KIND_FORCE_INT"},
};

std::map<CUpti_CallbackId, std::string> CALLBACK_API_DRIVER_ID_MAP = {
    {CUPTI_DRIVER_TRACE_CBID_INVALID, "INVALID"},
    {CUPTI_DRIVER_TRACE_CBID_cuInit, "cuInit"},
    {CUPTI_DRIVER_TRACE_CBID_cuDriverGetVersion, "cuDriverGetVersion"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGet, "cuDeviceGet"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetCount, "cuDeviceGetCount"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetName, "cuDeviceGetName"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceComputeCapability,
     "cuDeviceComputeCapability"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceTotalMem, "cuDeviceTotalMem"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetProperties, "cuDeviceGetProperties"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetAttribute, "cuDeviceGetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxCreate, "cuCtxCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxDestroy, "cuCtxDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxAttach, "cuCtxAttach"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxDetach, "cuCtxDetach"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxPushCurrent, "cuCtxPushCurrent"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxPopCurrent, "cuCtxPopCurrent"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxGetDevice, "cuCtxGetDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxSynchronize, "cuCtxSynchronize"},
    {CUPTI_DRIVER_TRACE_CBID_cuModuleLoad, "cuModuleLoad"},
    {CUPTI_DRIVER_TRACE_CBID_cuModuleLoadData, "cuModuleLoadData"},
    {CUPTI_DRIVER_TRACE_CBID_cuModuleLoadDataEx, "cuModuleLoadDataEx"},
    {CUPTI_DRIVER_TRACE_CBID_cuModuleLoadFatBinary, "cuModuleLoadFatBinary"},
    {CUPTI_DRIVER_TRACE_CBID_cuModuleUnload, "cuModuleUnload"},
    {CUPTI_DRIVER_TRACE_CBID_cuModuleGetFunction, "cuModuleGetFunction"},
    {CUPTI_DRIVER_TRACE_CBID_cuModuleGetGlobal, "cuModuleGetGlobal"},
    {CUPTI_DRIVER_TRACE_CBID_cu64ModuleGetGlobal, "cu64ModuleGetGlobal"},
    {CUPTI_DRIVER_TRACE_CBID_cuModuleGetTexRef, "cuModuleGetTexRef"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemGetInfo, "cuMemGetInfo"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemGetInfo, "cu64MemGetInfo"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAlloc, "cuMemAlloc"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemAlloc, "cu64MemAlloc"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAllocPitch, "cuMemAllocPitch"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemAllocPitch, "cu64MemAllocPitch"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemFree, "cuMemFree"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemFree, "cu64MemFree"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemGetAddressRange, "cuMemGetAddressRange"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemGetAddressRange, "cu64MemGetAddressRange"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAllocHost, "cuMemAllocHost"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemFreeHost, "cuMemFreeHost"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemHostAlloc, "cuMemHostAlloc"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemHostGetDevicePointer,
     "cuMemHostGetDevicePointer"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemHostGetDevicePointer,
     "cu64MemHostGetDevicePointer"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemHostGetFlags, "cuMemHostGetFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoD, "cuMemcpyHtoD"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemcpyHtoD, "cu64MemcpyHtoD"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoH, "cuMemcpyDtoH"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemcpyDtoH, "cu64MemcpyDtoH"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoD, "cuMemcpyDtoD"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemcpyDtoD, "cu64MemcpyDtoD"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoA, "cuMemcpyDtoA"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemcpyDtoA, "cu64MemcpyDtoA"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoD, "cuMemcpyAtoD"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemcpyAtoD, "cu64MemcpyAtoD"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoA, "cuMemcpyHtoA"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoH, "cuMemcpyAtoH"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoA, "cuMemcpyAtoA"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy2D, "cuMemcpy2D"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DUnaligned, "cuMemcpy2DUnaligned"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy3D, "cuMemcpy3D"},
    {CUPTI_DRIVER_TRACE_CBID_cu64Memcpy3D, "cu64Memcpy3D"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoDAsync, "cuMemcpyHtoDAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemcpyHtoDAsync, "cu64MemcpyHtoDAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoHAsync, "cuMemcpyDtoHAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemcpyDtoHAsync, "cu64MemcpyDtoHAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoDAsync, "cuMemcpyDtoDAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemcpyDtoDAsync, "cu64MemcpyDtoDAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoAAsync, "cuMemcpyHtoAAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoHAsync, "cuMemcpyAtoHAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DAsync, "cuMemcpy2DAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DAsync, "cuMemcpy3DAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cu64Memcpy3DAsync, "cu64Memcpy3DAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD8, "cuMemsetD8"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD8, "cu64MemsetD8"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD16, "cuMemsetD16"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD16, "cu64MemsetD16"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD32, "cuMemsetD32"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD32, "cu64MemsetD32"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D8, "cuMemsetD2D8"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D8, "cu64MemsetD2D8"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D16, "cuMemsetD2D16"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D16, "cu64MemsetD2D16"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D32, "cuMemsetD2D32"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D32, "cu64MemsetD2D32"},
    {CUPTI_DRIVER_TRACE_CBID_cuFuncSetBlockShape, "cuFuncSetBlockShape"},
    {CUPTI_DRIVER_TRACE_CBID_cuFuncSetSharedSize, "cuFuncSetSharedSize"},
    {CUPTI_DRIVER_TRACE_CBID_cuFuncGetAttribute, "cuFuncGetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuFuncSetCacheConfig, "cuFuncSetCacheConfig"},
    {CUPTI_DRIVER_TRACE_CBID_cuArrayCreate, "cuArrayCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuArrayGetDescriptor, "cuArrayGetDescriptor"},
    {CUPTI_DRIVER_TRACE_CBID_cuArrayDestroy, "cuArrayDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuArray3DCreate, "cuArray3DCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuArray3DGetDescriptor, "cuArray3DGetDescriptor"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefCreate, "cuTexRefCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefDestroy, "cuTexRefDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetArray, "cuTexRefSetArray"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddress, "cuTexRefSetAddress"},
    {CUPTI_DRIVER_TRACE_CBID_cu64TexRefSetAddress, "cu64TexRefSetAddress"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddress2D, "cuTexRefSetAddress2D"},
    {CUPTI_DRIVER_TRACE_CBID_cu64TexRefSetAddress2D, "cu64TexRefSetAddress2D"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetFormat, "cuTexRefSetFormat"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddressMode, "cuTexRefSetAddressMode"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetFilterMode, "cuTexRefSetFilterMode"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetFlags, "cuTexRefSetFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetAddress, "cuTexRefGetAddress"},
    {CUPTI_DRIVER_TRACE_CBID_cu64TexRefGetAddress, "cu64TexRefGetAddress"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetArray, "cuTexRefGetArray"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetAddressMode, "cuTexRefGetAddressMode"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetFilterMode, "cuTexRefGetFilterMode"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetFormat, "cuTexRefGetFormat"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetFlags, "cuTexRefGetFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuParamSetSize, "cuParamSetSize"},
    {CUPTI_DRIVER_TRACE_CBID_cuParamSeti, "cuParamSeti"},
    {CUPTI_DRIVER_TRACE_CBID_cuParamSetf, "cuParamSetf"},
    {CUPTI_DRIVER_TRACE_CBID_cuParamSetv, "cuParamSetv"},
    {CUPTI_DRIVER_TRACE_CBID_cuParamSetTexRef, "cuParamSetTexRef"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunch, "cuLaunch"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunchGrid, "cuLaunchGrid"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunchGridAsync, "cuLaunchGridAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventCreate, "cuEventCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventRecord, "cuEventRecord"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventQuery, "cuEventQuery"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventSynchronize, "cuEventSynchronize"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventDestroy, "cuEventDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventElapsedTime, "cuEventElapsedTime"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamCreate, "cuStreamCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamQuery, "cuStreamQuery"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamSynchronize, "cuStreamSynchronize"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamDestroy, "cuStreamDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsUnregisterResource,
     "cuGraphicsUnregisterResource"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsSubResourceGetMappedArray,
     "cuGraphicsSubResourceGetMappedArray"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceGetMappedPointer,
     "cuGraphicsResourceGetMappedPointer"},
    {CUPTI_DRIVER_TRACE_CBID_cu64GraphicsResourceGetMappedPointer,
     "cu64GraphicsResourceGetMappedPointer"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceSetMapFlags,
     "cuGraphicsResourceSetMapFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsMapResources, "cuGraphicsMapResources"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsUnmapResources,
     "cuGraphicsUnmapResources"},
    {CUPTI_DRIVER_TRACE_CBID_cuGetExportTable, "cuGetExportTable"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxSetLimit, "cuCtxSetLimit"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxGetLimit, "cuCtxGetLimit"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10GetDevice, "cuD3D10GetDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10CtxCreate, "cuD3D10CtxCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsD3D10RegisterResource,
     "cuGraphicsD3D10RegisterResource"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10RegisterResource,
     "cuD3D10RegisterResource"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10UnregisterResource,
     "cuD3D10UnregisterResource"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10MapResources, "cuD3D10MapResources"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10UnmapResources, "cuD3D10UnmapResources"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceSetMapFlags,
     "cuD3D10ResourceSetMapFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedArray,
     "cuD3D10ResourceGetMappedArray"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedPointer,
     "cuD3D10ResourceGetMappedPointer"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedSize,
     "cuD3D10ResourceGetMappedSize"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedPitch,
     "cuD3D10ResourceGetMappedPitch"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetSurfaceDimensions,
     "cuD3D10ResourceGetSurfaceDimensions"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D11GetDevice, "cuD3D11GetDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D11CtxCreate, "cuD3D11CtxCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsD3D11RegisterResource,
     "cuGraphicsD3D11RegisterResource"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9GetDevice, "cuD3D9GetDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9CtxCreate, "cuD3D9CtxCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsD3D9RegisterResource,
     "cuGraphicsD3D9RegisterResource"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9GetDirect3DDevice,
     "cuD3D9GetDirect3DDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9RegisterResource, "cuD3D9RegisterResource"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9UnregisterResource,
     "cuD3D9UnregisterResource"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9MapResources, "cuD3D9MapResources"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9UnmapResources, "cuD3D9UnmapResources"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceSetMapFlags,
     "cuD3D9ResourceSetMapFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetSurfaceDimensions,
     "cuD3D9ResourceGetSurfaceDimensions"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedArray,
     "cuD3D9ResourceGetMappedArray"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedPointer,
     "cuD3D9ResourceGetMappedPointer"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedSize,
     "cuD3D9ResourceGetMappedSize"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedPitch,
     "cuD3D9ResourceGetMappedPitch"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9Begin, "cuD3D9Begin"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9End, "cuD3D9End"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9RegisterVertexBuffer,
     "cuD3D9RegisterVertexBuffer"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9MapVertexBuffer, "cuD3D9MapVertexBuffer"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9UnmapVertexBuffer,
     "cuD3D9UnmapVertexBuffer"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9UnregisterVertexBuffer,
     "cuD3D9UnregisterVertexBuffer"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLCtxCreate, "cuGLCtxCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsGLRegisterBuffer,
     "cuGraphicsGLRegisterBuffer"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsGLRegisterImage,
     "cuGraphicsGLRegisterImage"},
    {CUPTI_DRIVER_TRACE_CBID_cuWGLGetDevice, "cuWGLGetDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLInit, "cuGLInit"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLRegisterBufferObject,
     "cuGLRegisterBufferObject"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObject, "cuGLMapBufferObject"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLUnmapBufferObject, "cuGLUnmapBufferObject"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLUnregisterBufferObject,
     "cuGLUnregisterBufferObject"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLSetBufferObjectMapFlags,
     "cuGLSetBufferObjectMapFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObjectAsync,
     "cuGLMapBufferObjectAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLUnmapBufferObjectAsync,
     "cuGLUnmapBufferObjectAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuVDPAUGetDevice, "cuVDPAUGetDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuVDPAUCtxCreate, "cuVDPAUCtxCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsVDPAURegisterVideoSurface,
     "cuGraphicsVDPAURegisterVideoSurface"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsVDPAURegisterOutputSurface,
     "cuGraphicsVDPAURegisterOutputSurface"},
    {CUPTI_DRIVER_TRACE_CBID_cuModuleGetSurfRef, "cuModuleGetSurfRef"},
    {CUPTI_DRIVER_TRACE_CBID_cuSurfRefCreate, "cuSurfRefCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuSurfRefDestroy, "cuSurfRefDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuSurfRefSetFormat, "cuSurfRefSetFormat"},
    {CUPTI_DRIVER_TRACE_CBID_cuSurfRefSetArray, "cuSurfRefSetArray"},
    {CUPTI_DRIVER_TRACE_CBID_cuSurfRefGetFormat, "cuSurfRefGetFormat"},
    {CUPTI_DRIVER_TRACE_CBID_cuSurfRefGetArray, "cuSurfRefGetArray"},
    {CUPTI_DRIVER_TRACE_CBID_cu64DeviceTotalMem, "cu64DeviceTotalMem"},
    {CUPTI_DRIVER_TRACE_CBID_cu64D3D10ResourceGetMappedPointer,
     "cu64D3D10ResourceGetMappedPointer"},
    {CUPTI_DRIVER_TRACE_CBID_cu64D3D10ResourceGetMappedSize,
     "cu64D3D10ResourceGetMappedSize"},
    {CUPTI_DRIVER_TRACE_CBID_cu64D3D10ResourceGetMappedPitch,
     "cu64D3D10ResourceGetMappedPitch"},
    {CUPTI_DRIVER_TRACE_CBID_cu64D3D10ResourceGetSurfaceDimensions,
     "cu64D3D10ResourceGetSurfaceDimensions"},
    {CUPTI_DRIVER_TRACE_CBID_cu64D3D9ResourceGetSurfaceDimensions,
     "cu64D3D9ResourceGetSurfaceDimensions"},
    {CUPTI_DRIVER_TRACE_CBID_cu64D3D9ResourceGetMappedPointer,
     "cu64D3D9ResourceGetMappedPointer"},
    {CUPTI_DRIVER_TRACE_CBID_cu64D3D9ResourceGetMappedSize,
     "cu64D3D9ResourceGetMappedSize"},
    {CUPTI_DRIVER_TRACE_CBID_cu64D3D9ResourceGetMappedPitch,
     "cu64D3D9ResourceGetMappedPitch"},
    {CUPTI_DRIVER_TRACE_CBID_cu64D3D9MapVertexBuffer,
     "cu64D3D9MapVertexBuffer"},
    {CUPTI_DRIVER_TRACE_CBID_cu64GLMapBufferObject, "cu64GLMapBufferObject"},
    {CUPTI_DRIVER_TRACE_CBID_cu64GLMapBufferObjectAsync,
     "cu64GLMapBufferObjectAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D11GetDevices, "cuD3D11GetDevices"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D11CtxCreateOnDevice,
     "cuD3D11CtxCreateOnDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10GetDevices, "cuD3D10GetDevices"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10CtxCreateOnDevice,
     "cuD3D10CtxCreateOnDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9GetDevices, "cuD3D9GetDevices"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9CtxCreateOnDevice,
     "cuD3D9CtxCreateOnDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemHostAlloc, "cu64MemHostAlloc"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD8Async, "cuMemsetD8Async"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD8Async, "cu64MemsetD8Async"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD16Async, "cuMemsetD16Async"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD16Async, "cu64MemsetD16Async"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD32Async, "cuMemsetD32Async"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD32Async, "cu64MemsetD32Async"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D8Async, "cuMemsetD2D8Async"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D8Async, "cu64MemsetD2D8Async"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D16Async, "cuMemsetD2D16Async"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D16Async, "cu64MemsetD2D16Async"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D32Async, "cuMemsetD2D32Async"},
    {CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D32Async, "cu64MemsetD2D32Async"},
    {CUPTI_DRIVER_TRACE_CBID_cu64ArrayCreate, "cu64ArrayCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cu64ArrayGetDescriptor, "cu64ArrayGetDescriptor"},
    {CUPTI_DRIVER_TRACE_CBID_cu64Array3DCreate, "cu64Array3DCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cu64Array3DGetDescriptor,
     "cu64Array3DGetDescriptor"},
    {CUPTI_DRIVER_TRACE_CBID_cu64Memcpy2D, "cu64Memcpy2D"},
    {CUPTI_DRIVER_TRACE_CBID_cu64Memcpy2DUnaligned, "cu64Memcpy2DUnaligned"},
    {CUPTI_DRIVER_TRACE_CBID_cu64Memcpy2DAsync, "cu64Memcpy2DAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxCreate_v2, "cuCtxCreate_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10CtxCreate_v2, "cuD3D10CtxCreate_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D11CtxCreate_v2, "cuD3D11CtxCreate_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9CtxCreate_v2, "cuD3D9CtxCreate_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLCtxCreate_v2, "cuGLCtxCreate_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuVDPAUCtxCreate_v2, "cuVDPAUCtxCreate_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuModuleGetGlobal_v2, "cuModuleGetGlobal_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemGetInfo_v2, "cuMemGetInfo_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAlloc_v2, "cuMemAlloc_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAllocPitch_v2, "cuMemAllocPitch_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemFree_v2, "cuMemFree_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemGetAddressRange_v2,
     "cuMemGetAddressRange_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemHostGetDevicePointer_v2,
     "cuMemHostGetDevicePointer_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy_v2, "cuMemcpy_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD8_v2, "cuMemsetD8_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD16_v2, "cuMemsetD16_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD32_v2, "cuMemsetD32_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D8_v2, "cuMemsetD2D8_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D16_v2, "cuMemsetD2D16_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D32_v2, "cuMemsetD2D32_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddress_v2, "cuTexRefSetAddress_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddress2D_v2,
     "cuTexRefSetAddress2D_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetAddress_v2, "cuTexRefGetAddress_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceGetMappedPointer_v2,
     "cuGraphicsResourceGetMappedPointer_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceTotalMem_v2, "cuDeviceTotalMem_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedPointer_v2,
     "cuD3D10ResourceGetMappedPointer_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedSize_v2,
     "cuD3D10ResourceGetMappedSize_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedPitch_v2,
     "cuD3D10ResourceGetMappedPitch_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetSurfaceDimensions_v2,
     "cuD3D10ResourceGetSurfaceDimensions_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetSurfaceDimensions_v2,
     "cuD3D9ResourceGetSurfaceDimensions_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedPointer_v2,
     "cuD3D9ResourceGetMappedPointer_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedSize_v2,
     "cuD3D9ResourceGetMappedSize_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedPitch_v2,
     "cuD3D9ResourceGetMappedPitch_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D9MapVertexBuffer_v2,
     "cuD3D9MapVertexBuffer_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObject_v2, "cuGLMapBufferObject_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObjectAsync_v2,
     "cuGLMapBufferObjectAsync_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemHostAlloc_v2, "cuMemHostAlloc_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuArrayCreate_v2, "cuArrayCreate_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuArrayGetDescriptor_v2,
     "cuArrayGetDescriptor_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuArray3DCreate_v2, "cuArray3DCreate_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuArray3DGetDescriptor_v2,
     "cuArray3DGetDescriptor_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoD_v2, "cuMemcpyHtoD_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoDAsync_v2, "cuMemcpyHtoDAsync_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoH_v2, "cuMemcpyDtoH_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoHAsync_v2, "cuMemcpyDtoHAsync_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoD_v2, "cuMemcpyDtoD_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoDAsync_v2, "cuMemcpyDtoDAsync_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoH_v2, "cuMemcpyAtoH_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoHAsync_v2, "cuMemcpyAtoHAsync_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoD_v2, "cuMemcpyAtoD_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoA_v2, "cuMemcpyDtoA_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoA_v2, "cuMemcpyAtoA_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy2D_v2, "cuMemcpy2D_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DUnaligned_v2, "cuMemcpy2DUnaligned_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DAsync_v2, "cuMemcpy2DAsync_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy3D_v2, "cuMemcpy3D_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DAsync_v2, "cuMemcpy3DAsync_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoA_v2, "cuMemcpyHtoA_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoAAsync_v2, "cuMemcpyHtoAAsync_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAllocHost_v2, "cuMemAllocHost_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWaitEvent, "cuStreamWaitEvent"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxGetApiVersion, "cuCtxGetApiVersion"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D10GetDirect3DDevice,
     "cuD3D10GetDirect3DDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuD3D11GetDirect3DDevice,
     "cuD3D11GetDirect3DDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxGetCacheConfig, "cuCtxGetCacheConfig"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxSetCacheConfig, "cuCtxSetCacheConfig"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemHostRegister, "cuMemHostRegister"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemHostUnregister, "cuMemHostUnregister"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxSetCurrent, "cuCtxSetCurrent"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxGetCurrent, "cuCtxGetCurrent"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy, "cuMemcpy"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAsync, "cuMemcpyAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunchKernel, "cuLaunchKernel"},
    {CUPTI_DRIVER_TRACE_CBID_cuProfilerStart, "cuProfilerStart"},
    {CUPTI_DRIVER_TRACE_CBID_cuProfilerStop, "cuProfilerStop"},
    {CUPTI_DRIVER_TRACE_CBID_cuPointerGetAttribute, "cuPointerGetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuProfilerInitialize, "cuProfilerInitialize"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceCanAccessPeer, "cuDeviceCanAccessPeer"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxEnablePeerAccess, "cuCtxEnablePeerAccess"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxDisablePeerAccess, "cuCtxDisablePeerAccess"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPeerRegister, "cuMemPeerRegister"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPeerUnregister, "cuMemPeerUnregister"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPeerGetDevicePointer,
     "cuMemPeerGetDevicePointer"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyPeer, "cuMemcpyPeer"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyPeerAsync, "cuMemcpyPeerAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DPeer, "cuMemcpy3DPeer"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DPeerAsync, "cuMemcpy3DPeerAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxDestroy_v2, "cuCtxDestroy_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxPushCurrent_v2, "cuCtxPushCurrent_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxPopCurrent_v2, "cuCtxPopCurrent_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventDestroy_v2, "cuEventDestroy_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamDestroy_v2, "cuStreamDestroy_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddress2D_v3,
     "cuTexRefSetAddress2D_v3"},
    {CUPTI_DRIVER_TRACE_CBID_cuIpcGetMemHandle, "cuIpcGetMemHandle"},
    {CUPTI_DRIVER_TRACE_CBID_cuIpcOpenMemHandle, "cuIpcOpenMemHandle"},
    {CUPTI_DRIVER_TRACE_CBID_cuIpcCloseMemHandle, "cuIpcCloseMemHandle"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetByPCIBusId, "cuDeviceGetByPCIBusId"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetPCIBusId, "cuDeviceGetPCIBusId"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLGetDevices, "cuGLGetDevices"},
    {CUPTI_DRIVER_TRACE_CBID_cuIpcGetEventHandle, "cuIpcGetEventHandle"},
    {CUPTI_DRIVER_TRACE_CBID_cuIpcOpenEventHandle, "cuIpcOpenEventHandle"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxSetSharedMemConfig,
     "cuCtxSetSharedMemConfig"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxGetSharedMemConfig,
     "cuCtxGetSharedMemConfig"},
    {CUPTI_DRIVER_TRACE_CBID_cuFuncSetSharedMemConfig,
     "cuFuncSetSharedMemConfig"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexObjectCreate, "cuTexObjectCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexObjectDestroy, "cuTexObjectDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexObjectGetResourceDesc,
     "cuTexObjectGetResourceDesc"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexObjectGetTextureDesc,
     "cuTexObjectGetTextureDesc"},
    {CUPTI_DRIVER_TRACE_CBID_cuSurfObjectCreate, "cuSurfObjectCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuSurfObjectDestroy, "cuSurfObjectDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuSurfObjectGetResourceDesc,
     "cuSurfObjectGetResourceDesc"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamAddCallback, "cuStreamAddCallback"},
    {CUPTI_DRIVER_TRACE_CBID_cuMipmappedArrayCreate, "cuMipmappedArrayCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuMipmappedArrayGetLevel,
     "cuMipmappedArrayGetLevel"},
    {CUPTI_DRIVER_TRACE_CBID_cuMipmappedArrayDestroy,
     "cuMipmappedArrayDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetMipmappedArray,
     "cuTexRefSetMipmappedArray"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetMipmapFilterMode,
     "cuTexRefSetMipmapFilterMode"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetMipmapLevelBias,
     "cuTexRefSetMipmapLevelBias"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetMipmapLevelClamp,
     "cuTexRefSetMipmapLevelClamp"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetMaxAnisotropy,
     "cuTexRefSetMaxAnisotropy"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetMipmappedArray,
     "cuTexRefGetMipmappedArray"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetMipmapFilterMode,
     "cuTexRefGetMipmapFilterMode"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetMipmapLevelBias,
     "cuTexRefGetMipmapLevelBias"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetMipmapLevelClamp,
     "cuTexRefGetMipmapLevelClamp"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetMaxAnisotropy,
     "cuTexRefGetMaxAnisotropy"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceGetMappedMipmappedArray,
     "cuGraphicsResourceGetMappedMipmappedArray"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexObjectGetResourceViewDesc,
     "cuTexObjectGetResourceViewDesc"},
    {CUPTI_DRIVER_TRACE_CBID_cuLinkCreate, "cuLinkCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuLinkAddData, "cuLinkAddData"},
    {CUPTI_DRIVER_TRACE_CBID_cuLinkAddFile, "cuLinkAddFile"},
    {CUPTI_DRIVER_TRACE_CBID_cuLinkComplete, "cuLinkComplete"},
    {CUPTI_DRIVER_TRACE_CBID_cuLinkDestroy, "cuLinkDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamCreateWithPriority,
     "cuStreamCreateWithPriority"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetPriority, "cuStreamGetPriority"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetFlags, "cuStreamGetFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxGetStreamPriorityRange,
     "cuCtxGetStreamPriorityRange"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAllocManaged, "cuMemAllocManaged"},
    {CUPTI_DRIVER_TRACE_CBID_cuGetErrorString, "cuGetErrorString"},
    {CUPTI_DRIVER_TRACE_CBID_cuGetErrorName, "cuGetErrorName"},
    {CUPTI_DRIVER_TRACE_CBID_cuOccupancyMaxActiveBlocksPerMultiprocessor,
     "cuOccupancyMaxActiveBlocksPerMultiprocessor"},
    {CUPTI_DRIVER_TRACE_CBID_cuCompilePtx, "cuCompilePtx"},
    {CUPTI_DRIVER_TRACE_CBID_cuBinaryFree, "cuBinaryFree"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamAttachMemAsync, "cuStreamAttachMemAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuPointerSetAttribute, "cuPointerSetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemHostRegister_v2, "cuMemHostRegister_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceSetMapFlags_v2,
     "cuGraphicsResourceSetMapFlags_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuLinkCreate_v2, "cuLinkCreate_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuLinkAddData_v2, "cuLinkAddData_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuLinkAddFile_v2, "cuLinkAddFile_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuOccupancyMaxPotentialBlockSize,
     "cuOccupancyMaxPotentialBlockSize"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLGetDevices_v2, "cuGLGetDevices_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxRetain,
     "cuDevicePrimaryCtxRetain"},
    {CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxRelease,
     "cuDevicePrimaryCtxRelease"},
    {CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxSetFlags,
     "cuDevicePrimaryCtxSetFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxReset,
     "cuDevicePrimaryCtxReset"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsEGLRegisterImage,
     "cuGraphicsEGLRegisterImage"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxGetFlags, "cuCtxGetFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxGetState,
     "cuDevicePrimaryCtxGetState"},
    {CUPTI_DRIVER_TRACE_CBID_cuEGLStreamConsumerConnect,
     "cuEGLStreamConsumerConnect"},
    {CUPTI_DRIVER_TRACE_CBID_cuEGLStreamConsumerDisconnect,
     "cuEGLStreamConsumerDisconnect"},
    {CUPTI_DRIVER_TRACE_CBID_cuEGLStreamConsumerAcquireFrame,
     "cuEGLStreamConsumerAcquireFrame"},
    {CUPTI_DRIVER_TRACE_CBID_cuEGLStreamConsumerReleaseFrame,
     "cuEGLStreamConsumerReleaseFrame"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoD_v2_ptds, "cuMemcpyHtoD_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoH_v2_ptds, "cuMemcpyDtoH_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoD_v2_ptds, "cuMemcpyDtoD_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoA_v2_ptds, "cuMemcpyDtoA_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoD_v2_ptds, "cuMemcpyAtoD_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoA_v2_ptds, "cuMemcpyHtoA_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoH_v2_ptds, "cuMemcpyAtoH_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoA_v2_ptds, "cuMemcpyAtoA_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy2D_v2_ptds, "cuMemcpy2D_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DUnaligned_v2_ptds,
     "cuMemcpy2DUnaligned_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy3D_v2_ptds, "cuMemcpy3D_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy_ptds, "cuMemcpy_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyPeer_ptds, "cuMemcpyPeer_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DPeer_ptds, "cuMemcpy3DPeer_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD8_v2_ptds, "cuMemsetD8_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD16_v2_ptds, "cuMemsetD16_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD32_v2_ptds, "cuMemsetD32_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D8_v2_ptds, "cuMemsetD2D8_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D16_v2_ptds, "cuMemsetD2D16_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D32_v2_ptds, "cuMemsetD2D32_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObject_v2_ptds,
     "cuGLMapBufferObject_v2_ptds"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAsync_ptsz, "cuMemcpyAsync_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoAAsync_v2_ptsz,
     "cuMemcpyHtoAAsync_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoHAsync_v2_ptsz,
     "cuMemcpyAtoHAsync_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoDAsync_v2_ptsz,
     "cuMemcpyHtoDAsync_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoHAsync_v2_ptsz,
     "cuMemcpyDtoHAsync_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoDAsync_v2_ptsz,
     "cuMemcpyDtoDAsync_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DAsync_v2_ptsz,
     "cuMemcpy2DAsync_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DAsync_v2_ptsz,
     "cuMemcpy3DAsync_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpyPeerAsync_ptsz, "cuMemcpyPeerAsync_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DPeerAsync_ptsz,
     "cuMemcpy3DPeerAsync_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD8Async_ptsz, "cuMemsetD8Async_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD16Async_ptsz, "cuMemsetD16Async_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD32Async_ptsz, "cuMemsetD32Async_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D8Async_ptsz, "cuMemsetD2D8Async_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D16Async_ptsz,
     "cuMemsetD2D16Async_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D32Async_ptsz,
     "cuMemsetD2D32Async_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetPriority_ptsz,
     "cuStreamGetPriority_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetFlags_ptsz, "cuStreamGetFlags_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWaitEvent_ptsz, "cuStreamWaitEvent_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamAddCallback_ptsz,
     "cuStreamAddCallback_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamAttachMemAsync_ptsz,
     "cuStreamAttachMemAsync_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamQuery_ptsz, "cuStreamQuery_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamSynchronize_ptsz,
     "cuStreamSynchronize_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventRecord_ptsz, "cuEventRecord_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunchKernel_ptsz, "cuLaunchKernel_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsMapResources_ptsz,
     "cuGraphicsMapResources_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsUnmapResources_ptsz,
     "cuGraphicsUnmapResources_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObjectAsync_v2_ptsz,
     "cuGLMapBufferObjectAsync_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuEGLStreamProducerConnect,
     "cuEGLStreamProducerConnect"},
    {CUPTI_DRIVER_TRACE_CBID_cuEGLStreamProducerDisconnect,
     "cuEGLStreamProducerDisconnect"},
    {CUPTI_DRIVER_TRACE_CBID_cuEGLStreamProducerPresentFrame,
     "cuEGLStreamProducerPresentFrame"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceGetMappedEglFrame,
     "cuGraphicsResourceGetMappedEglFrame"},
    {CUPTI_DRIVER_TRACE_CBID_cuPointerGetAttributes, "cuPointerGetAttributes"},
    {CUPTI_DRIVER_TRACE_CBID_cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags,
     "cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuOccupancyMaxPotentialBlockSizeWithFlags,
     "cuOccupancyMaxPotentialBlockSizeWithFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuEGLStreamProducerReturnFrame,
     "cuEGLStreamProducerReturnFrame"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetP2PAttribute,
     "cuDeviceGetP2PAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefSetBorderColor, "cuTexRefSetBorderColor"},
    {CUPTI_DRIVER_TRACE_CBID_cuTexRefGetBorderColor, "cuTexRefGetBorderColor"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAdvise, "cuMemAdvise"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue32, "cuStreamWaitValue32"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue32_ptsz,
     "cuStreamWaitValue32_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue32, "cuStreamWriteValue32"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue32_ptsz,
     "cuStreamWriteValue32_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamBatchMemOp, "cuStreamBatchMemOp"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamBatchMemOp_ptsz,
     "cuStreamBatchMemOp_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuNVNbufferGetPointer, "cuNVNbufferGetPointer"},
    {CUPTI_DRIVER_TRACE_CBID_cuNVNtextureGetArray, "cuNVNtextureGetArray"},
    {CUPTI_DRIVER_TRACE_CBID_cuNNSetAllocator, "cuNNSetAllocator"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPrefetchAsync, "cuMemPrefetchAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPrefetchAsync_ptsz,
     "cuMemPrefetchAsync_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventCreateFromNVNSync,
     "cuEventCreateFromNVNSync"},
    {CUPTI_DRIVER_TRACE_CBID_cuEGLStreamConsumerConnectWithFlags,
     "cuEGLStreamConsumerConnectWithFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemRangeGetAttribute, "cuMemRangeGetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemRangeGetAttributes,
     "cuMemRangeGetAttributes"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue64, "cuStreamWaitValue64"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue64_ptsz,
     "cuStreamWaitValue64_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue64, "cuStreamWriteValue64"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue64_ptsz,
     "cuStreamWriteValue64_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunchCooperativeKernel,
     "cuLaunchCooperativeKernel"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunchCooperativeKernel_ptsz,
     "cuLaunchCooperativeKernel_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventCreateFromEGLSync,
     "cuEventCreateFromEGLSync"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunchCooperativeKernelMultiDevice,
     "cuLaunchCooperativeKernelMultiDevice"},
    {CUPTI_DRIVER_TRACE_CBID_cuFuncSetAttribute, "cuFuncSetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetUuid, "cuDeviceGetUuid"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetCtx, "cuStreamGetCtx"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetCtx_ptsz, "cuStreamGetCtx_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuImportExternalMemory, "cuImportExternalMemory"},
    {CUPTI_DRIVER_TRACE_CBID_cuExternalMemoryGetMappedBuffer,
     "cuExternalMemoryGetMappedBuffer"},
    {CUPTI_DRIVER_TRACE_CBID_cuExternalMemoryGetMappedMipmappedArray,
     "cuExternalMemoryGetMappedMipmappedArray"},
    {CUPTI_DRIVER_TRACE_CBID_cuDestroyExternalMemory,
     "cuDestroyExternalMemory"},
    {CUPTI_DRIVER_TRACE_CBID_cuImportExternalSemaphore,
     "cuImportExternalSemaphore"},
    {CUPTI_DRIVER_TRACE_CBID_cuSignalExternalSemaphoresAsync,
     "cuSignalExternalSemaphoresAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuSignalExternalSemaphoresAsync_ptsz,
     "cuSignalExternalSemaphoresAsync_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuWaitExternalSemaphoresAsync,
     "cuWaitExternalSemaphoresAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuWaitExternalSemaphoresAsync_ptsz,
     "cuWaitExternalSemaphoresAsync_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuDestroyExternalSemaphore,
     "cuDestroyExternalSemaphore"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamBeginCapture, "cuStreamBeginCapture"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamBeginCapture_ptsz,
     "cuStreamBeginCapture_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamEndCapture, "cuStreamEndCapture"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamEndCapture_ptsz,
     "cuStreamEndCapture_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamIsCapturing, "cuStreamIsCapturing"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamIsCapturing_ptsz,
     "cuStreamIsCapturing_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphCreate, "cuGraphCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddKernelNode, "cuGraphAddKernelNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphKernelNodeGetParams,
     "cuGraphKernelNodeGetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddMemcpyNode, "cuGraphAddMemcpyNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphMemcpyNodeGetParams,
     "cuGraphMemcpyNodeGetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddMemsetNode, "cuGraphAddMemsetNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphMemsetNodeGetParams,
     "cuGraphMemsetNodeGetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphMemsetNodeSetParams,
     "cuGraphMemsetNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphNodeGetType, "cuGraphNodeGetType"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphGetRootNodes, "cuGraphGetRootNodes"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphNodeGetDependencies,
     "cuGraphNodeGetDependencies"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphNodeGetDependentNodes,
     "cuGraphNodeGetDependentNodes"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphInstantiate, "cuGraphInstantiate"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphLaunch, "cuGraphLaunch"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphLaunch_ptsz, "cuGraphLaunch_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecDestroy, "cuGraphExecDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphDestroy, "cuGraphDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddDependencies, "cuGraphAddDependencies"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphRemoveDependencies,
     "cuGraphRemoveDependencies"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphMemcpyNodeSetParams,
     "cuGraphMemcpyNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphKernelNodeSetParams,
     "cuGraphKernelNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphDestroyNode, "cuGraphDestroyNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphClone, "cuGraphClone"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphNodeFindInClone, "cuGraphNodeFindInClone"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddChildGraphNode,
     "cuGraphAddChildGraphNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddEmptyNode, "cuGraphAddEmptyNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunchHostFunc, "cuLaunchHostFunc"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunchHostFunc_ptsz, "cuLaunchHostFunc_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphChildGraphNodeGetGraph,
     "cuGraphChildGraphNodeGetGraph"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddHostNode, "cuGraphAddHostNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphHostNodeGetParams,
     "cuGraphHostNodeGetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetLuid, "cuDeviceGetLuid"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphHostNodeSetParams,
     "cuGraphHostNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphGetNodes, "cuGraphGetNodes"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphGetEdges, "cuGraphGetEdges"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetCaptureInfo, "cuStreamGetCaptureInfo"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetCaptureInfo_ptsz,
     "cuStreamGetCaptureInfo_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecKernelNodeSetParams,
     "cuGraphExecKernelNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamBeginCapture_v2,
     "cuStreamBeginCapture_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamBeginCapture_v2_ptsz,
     "cuStreamBeginCapture_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuThreadExchangeStreamCaptureMode,
     "cuThreadExchangeStreamCaptureMode"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetNvSciSyncAttributes,
     "cuDeviceGetNvSciSyncAttributes"},
    {CUPTI_DRIVER_TRACE_CBID_cuOccupancyAvailableDynamicSMemPerBlock,
     "cuOccupancyAvailableDynamicSMemPerBlock"},
    {CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxRelease_v2,
     "cuDevicePrimaryCtxRelease_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxReset_v2,
     "cuDevicePrimaryCtxReset_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxSetFlags_v2,
     "cuDevicePrimaryCtxSetFlags_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAddressReserve, "cuMemAddressReserve"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAddressFree, "cuMemAddressFree"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemCreate, "cuMemCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemRelease, "cuMemRelease"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemMap, "cuMemMap"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemUnmap, "cuMemUnmap"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemSetAccess, "cuMemSetAccess"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemExportToShareableHandle,
     "cuMemExportToShareableHandle"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemImportFromShareableHandle,
     "cuMemImportFromShareableHandle"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemGetAllocationGranularity,
     "cuMemGetAllocationGranularity"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemGetAllocationPropertiesFromHandle,
     "cuMemGetAllocationPropertiesFromHandle"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemGetAccess, "cuMemGetAccess"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamSetFlags, "cuStreamSetFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamSetFlags_ptsz, "cuStreamSetFlags_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecUpdate, "cuGraphExecUpdate"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecMemcpyNodeSetParams,
     "cuGraphExecMemcpyNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecMemsetNodeSetParams,
     "cuGraphExecMemsetNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecHostNodeSetParams,
     "cuGraphExecHostNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemRetainAllocationHandle,
     "cuMemRetainAllocationHandle"},
    {CUPTI_DRIVER_TRACE_CBID_cuFuncGetModule, "cuFuncGetModule"},
    {CUPTI_DRIVER_TRACE_CBID_cuIpcOpenMemHandle_v2, "cuIpcOpenMemHandle_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxResetPersistingL2Cache,
     "cuCtxResetPersistingL2Cache"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphKernelNodeCopyAttributes,
     "cuGraphKernelNodeCopyAttributes"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphKernelNodeGetAttribute,
     "cuGraphKernelNodeGetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphKernelNodeSetAttribute,
     "cuGraphKernelNodeSetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamCopyAttributes, "cuStreamCopyAttributes"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamCopyAttributes_ptsz,
     "cuStreamCopyAttributes_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetAttribute, "cuStreamGetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetAttribute_ptsz,
     "cuStreamGetAttribute_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamSetAttribute, "cuStreamSetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamSetAttribute_ptsz,
     "cuStreamSetAttribute_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphInstantiate_v2, "cuGraphInstantiate_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetTexture1DLinearMaxWidth,
     "cuDeviceGetTexture1DLinearMaxWidth"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphUpload, "cuGraphUpload"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphUpload_ptsz, "cuGraphUpload_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuArrayGetSparseProperties,
     "cuArrayGetSparseProperties"},
    {CUPTI_DRIVER_TRACE_CBID_cuMipmappedArrayGetSparseProperties,
     "cuMipmappedArrayGetSparseProperties"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemMapArrayAsync, "cuMemMapArrayAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemMapArrayAsync_ptsz,
     "cuMemMapArrayAsync_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecChildGraphNodeSetParams,
     "cuGraphExecChildGraphNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventRecordWithFlags, "cuEventRecordWithFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuEventRecordWithFlags_ptsz,
     "cuEventRecordWithFlags_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddEventRecordNode,
     "cuGraphAddEventRecordNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddEventWaitNode,
     "cuGraphAddEventWaitNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphEventRecordNodeGetEvent,
     "cuGraphEventRecordNodeGetEvent"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphEventWaitNodeGetEvent,
     "cuGraphEventWaitNodeGetEvent"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphEventRecordNodeSetEvent,
     "cuGraphEventRecordNodeSetEvent"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphEventWaitNodeSetEvent,
     "cuGraphEventWaitNodeSetEvent"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecEventRecordNodeSetEvent,
     "cuGraphExecEventRecordNodeSetEvent"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecEventWaitNodeSetEvent,
     "cuGraphExecEventWaitNodeSetEvent"},
    {CUPTI_DRIVER_TRACE_CBID_cuArrayGetPlane, "cuArrayGetPlane"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAllocAsync, "cuMemAllocAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAllocAsync_ptsz, "cuMemAllocAsync_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemFreeAsync, "cuMemFreeAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemFreeAsync_ptsz, "cuMemFreeAsync_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPoolTrimTo, "cuMemPoolTrimTo"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPoolSetAttribute, "cuMemPoolSetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPoolGetAttribute, "cuMemPoolGetAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPoolSetAccess, "cuMemPoolSetAccess"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetDefaultMemPool,
     "cuDeviceGetDefaultMemPool"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPoolCreate, "cuMemPoolCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPoolDestroy, "cuMemPoolDestroy"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceSetMemPool, "cuDeviceSetMemPool"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetMemPool, "cuDeviceGetMemPool"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAllocFromPoolAsync,
     "cuMemAllocFromPoolAsync"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemAllocFromPoolAsync_ptsz,
     "cuMemAllocFromPoolAsync_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPoolExportToShareableHandle,
     "cuMemPoolExportToShareableHandle"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPoolImportFromShareableHandle,
     "cuMemPoolImportFromShareableHandle"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPoolExportPointer, "cuMemPoolExportPointer"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPoolImportPointer, "cuMemPoolImportPointer"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemPoolGetAccess, "cuMemPoolGetAccess"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddExternalSemaphoresSignalNode,
     "cuGraphAddExternalSemaphoresSignalNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExternalSemaphoresSignalNodeGetParams,
     "cuGraphExternalSemaphoresSignalNodeGetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExternalSemaphoresSignalNodeSetParams,
     "cuGraphExternalSemaphoresSignalNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddExternalSemaphoresWaitNode,
     "cuGraphAddExternalSemaphoresWaitNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExternalSemaphoresWaitNodeGetParams,
     "cuGraphExternalSemaphoresWaitNodeGetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExternalSemaphoresWaitNodeSetParams,
     "cuGraphExternalSemaphoresWaitNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecExternalSemaphoresSignalNodeSetParams,
     "cuGraphExecExternalSemaphoresSignalNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecExternalSemaphoresWaitNodeSetParams,
     "cuGraphExecExternalSemaphoresWaitNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGetProcAddress, "cuGetProcAddress"},
    {CUPTI_DRIVER_TRACE_CBID_cuFlushGPUDirectRDMAWrites,
     "cuFlushGPUDirectRDMAWrites"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphDebugDotPrint, "cuGraphDebugDotPrint"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetCaptureInfo_v2,
     "cuStreamGetCaptureInfo_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamGetCaptureInfo_v2_ptsz,
     "cuStreamGetCaptureInfo_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamUpdateCaptureDependencies,
     "cuStreamUpdateCaptureDependencies"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamUpdateCaptureDependencies_ptsz,
     "cuStreamUpdateCaptureDependencies_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuUserObjectCreate, "cuUserObjectCreate"},
    {CUPTI_DRIVER_TRACE_CBID_cuUserObjectRetain, "cuUserObjectRetain"},
    {CUPTI_DRIVER_TRACE_CBID_cuUserObjectRelease, "cuUserObjectRelease"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphRetainUserObject,
     "cuGraphRetainUserObject"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphReleaseUserObject,
     "cuGraphReleaseUserObject"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddMemAllocNode, "cuGraphAddMemAllocNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddMemFreeNode, "cuGraphAddMemFreeNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGraphMemTrim, "cuDeviceGraphMemTrim"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetGraphMemAttribute,
     "cuDeviceGetGraphMemAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceSetGraphMemAttribute,
     "cuDeviceSetGraphMemAttribute"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphInstantiateWithFlags,
     "cuGraphInstantiateWithFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetExecAffinitySupport,
     "cuDeviceGetExecAffinitySupport"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxCreate_v3, "cuCtxCreate_v3"},
    {CUPTI_DRIVER_TRACE_CBID_cuCtxGetExecAffinity, "cuCtxGetExecAffinity"},
    {CUPTI_DRIVER_TRACE_CBID_cuDeviceGetUuid_v2, "cuDeviceGetUuid_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphMemAllocNodeGetParams,
     "cuGraphMemAllocNodeGetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphMemFreeNodeGetParams,
     "cuGraphMemFreeNodeGetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphNodeSetEnabled, "cuGraphNodeSetEnabled"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphNodeGetEnabled, "cuGraphNodeGetEnabled"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunchKernelEx, "cuLaunchKernelEx"},
    {CUPTI_DRIVER_TRACE_CBID_cuLaunchKernelEx_ptsz, "cuLaunchKernelEx_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuArrayGetMemoryRequirements,
     "cuArrayGetMemoryRequirements"},
    {CUPTI_DRIVER_TRACE_CBID_cuMipmappedArrayGetMemoryRequirements,
     "cuMipmappedArrayGetMemoryRequirements"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphInstantiateWithParams,
     "cuGraphInstantiateWithParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphInstantiateWithParams_ptsz,
     "cuGraphInstantiateWithParams_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecGetFlags, "cuGraphExecGetFlags"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue32_v2, "cuStreamWaitValue32_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue32_v2_ptsz,
     "cuStreamWaitValue32_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue64_v2, "cuStreamWaitValue64_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue64_v2_ptsz,
     "cuStreamWaitValue64_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue32_v2,
     "cuStreamWriteValue32_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue32_v2_ptsz,
     "cuStreamWriteValue32_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue64_v2,
     "cuStreamWriteValue64_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue64_v2_ptsz,
     "cuStreamWriteValue64_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamBatchMemOp_v2, "cuStreamBatchMemOp_v2"},
    {CUPTI_DRIVER_TRACE_CBID_cuStreamBatchMemOp_v2_ptsz,
     "cuStreamBatchMemOp_v2_ptsz"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphAddBatchMemOpNode,
     "cuGraphAddBatchMemOpNode"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphBatchMemOpNodeGetParams,
     "cuGraphBatchMemOpNodeGetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphBatchMemOpNodeSetParams,
     "cuGraphBatchMemOpNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuGraphExecBatchMemOpNodeSetParams,
     "cuGraphExecBatchMemOpNodeSetParams"},
    {CUPTI_DRIVER_TRACE_CBID_cuModuleGetLoadingMode, "cuModuleGetLoadingMode"},
    {CUPTI_DRIVER_TRACE_CBID_cuMemGetHandleForAddressRange,
     "cuMemGetHandleForAddressRange"},
    {CUPTI_DRIVER_TRACE_CBID_cuOccupancyMaxPotentialClusterSize,
     "cuOccupancyMaxPotentialClusterSize"},
    {CUPTI_DRIVER_TRACE_CBID_cuOccupancyMaxActiveClusters,
     "cuOccupancyMaxActiveClusters"},
    {CUPTI_DRIVER_TRACE_CBID_SIZE, "SIZE"},
    {CUPTI_DRIVER_TRACE_CBID_FORCE_INT, "FORCE_INT"}};